<FloatLayout>:
    
    background_color: 0,0,0,0
    #canvas.before:
    #    Color:
    #        # r, g, b, alpha (1 = full)
    #        rgba: (.3, .6, .7, 1)
    #    RoundedRectangle:
    #        # pos_hint = {"x": 0.1, "y": 0.75}
    #        pos: self.pos
    #        size: self.size
    #        radius: [(50, 50), (50, 50), (50, 50), (50, 50)]
    #        #radius: self.radius
    
    Button:
        text: "Up"
        font_size: 40
        background_color: [0.5, 0.5,.95]
        #background_normal: ""
        back_color: (1, 0.75, 0.50, 0,75)
        border_radius: [25]
        pos_hint: {"x":0.20, "y":0.20}
        size_hint: [0.40, 0.20]
        
        #Canvas:
        #    Color:
        #        rgba: (.3, .6, .7, 1)
        #    RoundedRectangle:
        #        pos: self.pos
        #        size: self.size
        #        radius: self.border_radius
    
    #on_release:
    #    app.root.current = "second"
    #    root.manager.transition.direction = "le
        